spring:
  config:
    import: "optional:configserver:"  # ??Config Server?????
  application:
    name: EurekaServer
  cloud:
    config:
      uri: http://127.0.0.1:8888  # Config Server??????
      #uri: http://100.10.10.3:8888  # docker???
      name: EurekaServer  # ???????????Config Server????
      profile: dev  # ?????????Config Server????
      label: master  # ?????Git?????????????????????????????????????`master`
